global:
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 60m
  receiver: 'telepush'
receivers:
# - name: 'email'
#   email_configs:
#   - to: 'user@gmail.com' # адрес_электронной_почты_получателя
#     from: 'user@gmail.com' # адрес_электронной_почты_отправителя
#     smarthost: 'smtp.gmail.com:587' # SMTP_хост:порт
#     auth_username: 'user@gmail.com' # имя_пользователя
#     auth_identity: 'user@gmail.com' # имя_пользователя
#     auth_password: '<user password or app password>' # user password or app password for gmail
#
#  - name: 'telegram'
#    telegram_configs:
#    - bot_token: '<bot token>'
#      api_url: 'https://api.telegram.org'
#      chat_id: <chat id> # example: -657898  !withouth quotes
#      message:  "Alertname: {{ .GroupLabels.alertname }}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
#      parse_mode: ''
#
  - name: 'telepush'
    webhook_configs:
    - url: 'https://telepush.dev/api/inlets/alertmanager/<bot token>' # add your Telepush token here
      http_config:
